### ISSUE TITLE
Audio visualisation

### ISSUE THREAD

**Issue by zatovagul** [halildurmus/siri_wave#1]
Hi am getting data as WaveForm or FFT. in Uint8List or List<int> how to show wave of this data?

**Comment by halildurmus** [comment]
There is an `amplitude` parameter in the `SiriWaveController`, that controls the `height` of the waves.

If your data consists of double numbers and is in the [0,1] range, you can use them in `SiriWave` widget by calling `controller.setAmplitude(amplitude)` function. If not, you should first normalize those numbers to the [0,1] range.

Check out the live demo [here](https://halildurmus.github.io/siri_wave) and play with the amplitude slider to see if that's what you want and better understand what I mean.

**Comment by zatovagul** [comment]
> There is an `amplitude` parameter in the `SiriWaveController`, that controls the `height` of the waves.
> 
> If your data consists of double numbers and is in the [0,1] range, you can use them in `SiriWave` widget by calling `controller.setAmplitude(amplitude)` function. If not, you should first normalize those numbers to the [0,1] range.
> 
> Check out the live demo [here](https://halildurmus.github.io/siri_wave) and play with the amplitude slider to see if that's what you want and better understand what I mean.

Yes I was trying to do this, but it doesn't look normal. Animation not working like it should.
I get the stream of audio buffer as Uint8List, in 1 second I think I get more than 10-20 Uint8Lists.

I recorded the video, at the start I Change amplitude every 0.3 sec. At the end I just setAmplitude for 1


https://streamable.com/bvdlpw
