### ISSUE TITLE
Can IOS9 wave be respond with .wav file?

### ISSUE THREAD

**Issue by dongyangTHU** [halildurmus/siri_wave#10]
HI, I tried to get the frequency from audio file, then I tried to put the frequency to the ios9 wvae to visualize, however it seems not work, is there any way to make IOS9 wave respond due to the audio file?

**Comment by halildurmus** [comment]
The `frequency` property only works with the *iOS 7 Siri-style* waveform. What you're looking for is probably the `amplitude` property.

Check out the live demo [here](https://halildurmus.github.io/siri_wave) and play with the `amplitude` slider to see if that's what you want.
