### ISSUE TITLE
New SIRI style

### ISSUE THREAD

**Issue by kekko7072** [halildurmus/siri_wave#2]
Hey @halildurmus  great package,
can you add the new version of siri?

![IMG_EA9C94625BB0-1](https://user-images.githubusercontent.com/32552589/195307769-e8c99d77-0edb-453e-ad60-5ba2de6c6890.jpeg)

**Comment by halildurmus** [comment]
Thanks! I really like this animation, but it's too complicated for me to implement. Sorry!
