### ISSUE TITLE
feat: ios 18 siri animations

### ISSUE THREAD

**Issue by bhavukspilll** [halildurmus/siri_wave#33]
### Description

ios 18+ in apple AI introduced new siri animations. 
![image](https://github.com/user-attachments/assets/976ecd02-7f33-4e04-b43f-13e46398d18e)

### Requirements

- [ ] All CI/CD checks are passing.
- [ ] There is no drop in the test coverage percentage.

### Additional Context

New apple Intelligence siri animations

**Comment by halildurmus** [comment]
I have no plans to support the latest animations, sorry.
